name: deploy to wolke

on:
  push:
    branches:
      - master

jobs:
  deploy-to-wolke:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v2
      - name: install dependencies
        run: yarn install
      - name: build app
        run: yarn build
      - name: copy ssh key
        run: |
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: clear server directory
        run: |
          ssh root@${{ secrets.SERVER_ADDRESS }} <<"ENDSSH"
          rm -rf /root/apps/tsc/
          mkdir -p /root/apps/tsc/
          ENDSSH
      - name: deploy build
        run: |
          cd build/
          scp -r * root@${{ secrets.SERVER_ADDRESS }}:/root/apps/tsc/